# This override file should be used when running this service in isolation
# to provide dependencies and expose ports for local testing

services:
  ? ffc-debugger
  : build:
      target: development
    image: ffc-debugger-development
    container_name: ffc-debugger-development
    ports:
      - "3000:3000"
      - "9229:9229"
    volumes:
      - ./app:/home/node/app
      - ./test:/home/node/test
      - ./scripts:/home/node/scripts
      - ./package.json:/home/node/package.json
      

  ? ffc-debugger-postgres
  : ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: