# This override file should be used when running automated tests so
# that test output is saved to the host

services:
  ? ffc-debugger
  : build:
      target: development
    image: ffc-debugger-development
    container_name: ffc-debugger-test
    command: echo "Nodejs testing not required for debug container"
